const { test, expect } = require('@playwright/test');
const crypto = require('node:crypto');

test('ACME settings persist, preserve unsaved edits, and approve registered accounts', async ({ page }) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/settings');
  await page.getByLabel('Admin token', { exact: true }).fill('browser-test-admin-token-not-for-deployment');
  await page.getByRole('button', { name: 'Open administration' }).click();
  await expect(page.getByRole('heading', { name: 'Settings', exact: true })).toBeVisible();
  await expect(page.getByLabel('Access mode')).toHaveValue('disabled');
  await expect(page.locator('#acme-base-url')).not.toHaveValue('');
  await page.getByLabel('Access mode').selectOption('trusted_network');
  await page.getByLabel('Allowed client networks').fill('not-a-network');
  await page.locator('#acme-terms').check();
  await page.getByRole('button', { name: 'Save ACME settings' }).click();
  await expect(page.locator('#acme-settings-error')).toContainText('CIDRs');
  await page.getByLabel('Allowed client networks').fill('127.0.0.1/32');
  await page.getByLabel('Allowed certificate domains (optional)').fill('example.com\n*.example.com');
  await page.getByRole('button', { name: 'Save ACME settings' }).click();
  await expect(page.locator('#notice')).toHaveText('ACME settings saved.');
  await expect(page.locator('#acme-connection-status')).toContainText('Staging');
  const directory = await page.getByLabel('ACME directory URL').inputValue();
  const command = await page.getByLabel('Certbot example').inputValue();
  expect(command).toContain('--server');
  expect(command).toContain('\\\n');
  expect(command).not.toContain('TOKEN');
  const response = await page.request.get(directory);
  expect(response.status()).toBe(200);
  const endpoints = await response.json();
  // Live account registration against the local app; no upstream issuance is requested.
  const { privateKey, publicKey } = crypto.generateKeyPairSync('ec', { namedCurve: 'prime256v1' });
  const nonceResponse = await page.request.head(endpoints.newNonce);
  const header = Buffer.from(JSON.stringify({ alg: 'ES256', url: endpoints.newAccount, nonce: nonceResponse.headers()['replay-nonce'], jwk: publicKey.export({ format: 'jwk' }) })).toString('base64url');
  const payload = Buffer.from(JSON.stringify({ termsOfServiceAgreed: true, contact: ['mailto:test@example.com'] })).toString('base64url');
  const signature = crypto.sign('sha256', Buffer.from(`${header}.${payload}`), { key: privateKey, dsaEncoding: 'ieee-p1363' }).toString('base64url');
  const registration = await page.request.post(endpoints.newAccount, { headers: { 'content-type': 'application/jose+json' }, data: { protected: header, payload, signature } });
  expect(registration.status()).toBe(201);
  await page.getByLabel('Access mode').selectOption('approved_accounts');
  await page.getByRole('button', { name: 'Save ACME settings' }).click();
  await expect(page.getByRole('button', { name: 'Approve', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Approve', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Remove approval', exact: true })).toBeVisible();
  await page.getByLabel('Allowed certificate domains (optional)').fill('unsaved.example.com');
  await page.locator('#acme-settings-refresh').click();
  await expect(page.getByLabel('Allowed certificate domains (optional)')).toHaveValue('unsaved.example.com');
  await page.reload();
  await page.getByLabel('Admin token', { exact: true }).fill('browser-test-admin-token-not-for-deployment');
  await page.getByRole('button', { name: 'Open administration' }).click();
  await expect(page.getByLabel('Access mode')).toHaveValue('approved_accounts');
  await expect(page.getByLabel('Allowed certificate domains (optional)')).toHaveValue('example.com\n*.example.com');
  await expect(page.getByRole('button', { name: 'Remove approval', exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/acme-settings-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Remove approval', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Approve', exact: true })).toBeVisible();
  await page.getByLabel('Access mode').selectOption('disabled');
  await page.getByRole('button', { name: 'Save ACME settings' }).click();
  await expect(page.locator('#acme-connection-status')).toContainText('enabled access mode');
  expect((await page.request.get(directory)).status()).toBe(404);
  expect(errors).toEqual([]);
});
